### ISSUE TITLE
Możliwość rejestracji i logowania.

### ISSUE THREAD

**Issue by srzeppa** [mklemarczyk/yii-prezentacja#10]
Jak zrobić (tabele w bazie danych itp itd, ogólnie chodzi o wszystko), by była możliwość rejestracji i logowania użytkowników w aplikacji?
(͡° ͜ʖ ͡°)

**Comment by mklemarczyk** [comment]
W tym celu musisz użyć narzędzia migracji. Odpowiada ono za automatyczne tworzenie tabel w bazie danych oraz ich aktualizację.
W podstawowym szkielecie aplikacji jest opisana migracja tworząca tabelę user, więc nie możesz posiadać takiej tabeli w bazie przed wykonaniem skryptu.

Skrypt możesz wywołać zaczynając od `start.bat` aby zainicjować zmienną z PHP.
A następnie należy wywołać polecenie migracji:

```
yii.bat migrate
```
