### ISSUE TITLE
Problem z umieszczeniem wielu danych w jednym dropDownList-ach

### ISSUE THREAD

**Issue by romety2** [mklemarczyk/yii-prezentacja#11]
Witam!

Mam utworzoną relacje w taki sposob ze id_osoba jest kluczem obcym, w mojej dropDownLiscie wypadalo by wyswitlic imie  oraz nazwisko, jednka nie wiem jak to zrobic. Jakbyś umiał mi pomóc prosił bym o odpowiedź.

**Comment by mklemarczyk** [comment]
Odpowiedź znajduje się w #3.

**Comment by romety2** [comment]
Nie wiedzialem, ze php jest taki madry :+1:  dzieki za pomoc
