### ISSUE TITLE
Usuwanie rekordu, do którego jest odwołanie w innej tabeli

### ISSUE THREAD

**Issue by mawalca** [mklemarczyk/yii-prezentacja#12]
Kiedy klikam, by usunąć jakiś element, do którego odwołuje się inna tabela w kluczu obcym, wyświetla się cała strona, opisująca błędy. Nie chcę ustawiać w bazie, by usuwanie było kaskadowe (co by usunęło ten problem). Stąd moje pytanie, czy można zrobić tak, by zamiast tej strony z błędami wyskakiwało małe okienko z informacją, że nie da się usunąć elementu? Jeśli się da, to jak to zrobić?

**Comment by mklemarczyk** [comment]
W akcji actionDelete możesz użyć konstrukcji try catch w celu wyłapania błędu, a następnie użyć widgetu Alert do zakomunikowania błędu.

``` php
    /**
     * Deletes an existing Page model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        try{
            $model->delete();
            return $this->redirect(['index']);
        }catch(\Exception $ex){
            Yii::$app->getSession()->setFlash('error', 'Nie można usunąć z powodu dowiazania');
        }
        return $this->goBack();
    }
```

**Comment by mawala** [comment]
Od razu pokazuje się błąd:
```
syntax error, unexpected '{', expecting '('
```

**Comment by mklemarczyk** [comment]
a no tak bo się pisze przecież ```}catch(){```

**Comment by mawala** [comment]
No i teraz wszystko pięknie działa. Dziękuję bardzo za pomoc
