### ISSUE TITLE
Jak zaktualizować PHP?

### ISSUE THREAD

**Issue by goorskyy** [mklemarczyk/yii-prezentacja#14]
Chciałbym zaktualizować wersję PHP w USBWebServer

**Comment by mklemarczyk** [comment]
Musisz ściągnąć archiwum z interpreterem PHP ze strony http://php.net

Na przykład: http://windows.php.net/downloads/releases/php-5.4.40-Win32-VC9-x86.zip
1. Wyłącz serwer USBWebServer
2. Stwórz archiwum z folderu **php**
3. Pobierz nową wersję PHP
4. Usuń zawartość folderu **php**
5. Wklej pliki nowego PHP do folderu **php**

Na koniec zapisz jeszcze raz konfigurację serwera USBWebServer (okno aplikacji)
