### ISSUE TITLE
Dane zamiast numeru id klucza obcego

### ISSUE THREAD

**Issue by Strugacki** [mklemarczyk/yii-prezentacja#16]
Jak rozwiązać problem z ukrywaniem kluczy obcych oraz głównych w widoku.

**Comment by mklemarczyk** [comment]
Masz na myśli by wyświetlić dane pracownika zamiast jego id?
Możesz podać zawartość pliku z widokiem?

**Comment by Strugacki** [comment]
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Wypożyczenia';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="wypozyczenie-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Dodaj Wypożyczenie', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'Identyfikator_wypozyczenia',
            'data_wypozyczenia',
            'data_zwrotu',
            'cena_wypozyczenia',
            'Identyfikator_pracownika',
            'Identyfikator_klienta',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

**Comment by Strugacki** [comment]
Tak, dokładnie to mam na myśli.

Plik widoku:

``` php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Wypożyczenia';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="wypozyczenie-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Dodaj Wypożyczenie', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'Identyfikator_wypozyczenia',
            'data_wypozyczenia',
            'data_zwrotu',
            'cena_wypozyczenia',
            'Identyfikator_pracownika',
            'Identyfikator_klienta',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>
```

**Comment by mklemarczyk** [comment]
Aby ukryć pola wystarczy je usunąć tutaj z atrybutów.

``` php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Wypożyczenia';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="wypozyczenie-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Dodaj Wypożyczenie', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'Identyfikator_wypozyczenia',
            'data_wypozyczenia',
            'data_zwrotu',
            'cena_wypozyczenia',
            // 'Identyfikator_pracownika',
            // 'Identyfikator_klienta',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>
```

**Comment by Strugacki** [comment]
Chodziło bardziej o listę z imionami zamiast identyfikatorów

**Comment by mklemarczyk** [comment]
Możesz podać zawartość pierwszego komentarza modelu wypozyczenia?

**Comment by Strugacki** [comment]
``` php
/**
 * This is the model class for table "wypozyczenie".
 *
 * @property integer $Identyfikator_wypozyczenia
 * @property string $data_wypozyczenia
 * @property string $data_zwrotu
 * @property string $cena_wypozyczenia
 * @property integer $Identyfikator_pracownika
 * @property integer $Identyfikator_klienta
 *
 * @property Klient $identyfikatorKlienta
 * @property Pracownik $identyfikatorPracownika
 * @property WypozyczenieKajaku[] $wypozyczenieKajakus
 * @property Kajak[] $identyfiaktorKajakus
 */
```

**Comment by mklemarczyk** [comment]
To wystarczy zamiast `'Identyfikator_pracownika'` podać nazwę relacji oraz nazwę pola do wyświetlenia np. `'identyfikatorPracownika.imie'`. Zakładając, że pole **imie** istnieje w modelu **pracownik**.
