### ISSUE TITLE
Dodanie obrazka w widoku (eg. site/home)

### ISSUE THREAD

**Issue by martin123154** [mklemarczyk/yii-prezentacja#17]
Witam, Mam pytanie. Jak dodać jakiś obrazek na główną strone aplikacji?

**Comment by mklemarczyk** [comment]
Jeśli chcesz dodać stały obrazek na główną stronę to:
1. Musisz go skopiować do katalogu **/frontent/web/images**, Katalog **images** to tylko zalecenie, możesz go dowolnie nazwać.
2. W pliku [**widoku**](http://www.yiiframework.com/doc-2.0/guide-structure-views.html) **/forntend/views/site/index.php** wyświetlić obrazek poleceniem:

``` php
<?= Html::img('images/nazwa_obrazka.png'); ?>
```

Obrazek może być dowolnym plikiem graficznym (jpeg, jpg, png, svg, bmp, gif itp.), jego działanie zależy tylko i wyłącznie od przeglądarki.
