### ISSUE TITLE
Wybranie tylko zatrudnionych pracowników (Formularz - DropDownList)

### ISSUE THREAD

**Issue by romety2** [mklemarczyk/yii-prezentacja#18]
Witam mam pytanie, czy jest możliwe zrealizowanie DropDownListy w taki sposób by nie wyświetlała wszystkich danych z tabeli, dla przykładu mam tabele pracownik oraz kolumnę zwolniony (typu bool) i nie chce mieć na liście pracowników o wartości true w danej kolumnie :)

**Comment by mklemarczyk** [comment]
Należy w miejscu pobierania danych zastosować funkcję where.
Należy jej użyć po funkcji find().

Na przykład:

``` php
        $samoloty = Samolot::find()->where(['model' => 'F16'])->all();
```

Na przykład:

``` php
        $samoloty = Samolot::find()
        ->where(['and', ['>', 'rok_produkcji', '2014-01-01'], ['<=', 'rok_produkcji',  '2015-06-02']])
        ->all();
```

:information_source: Więcej o funkcji where: http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html#where
