### ISSUE TITLE
Powtarzanie danych - pola z wartościami unikatowymi

### ISSUE THREAD

**Issue by martin123154** [mklemarczyk/yii-prezentacja#19]
Jak wykonać coś takiego że mając UNIQUE przy kolumnie powiedzmy PESEL, przy wpisaniu tego samego drugi raz nie wyświetlało strony z błedami tylko jakiś stosowny komunikat?

**Comment by mklemarczyk** [comment]
Należy w tym celu poinformować model, że dane pole może mieć tylko unikatowe wartości za pomocą validatora: http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html

Przykład zastosowania w modelu:

``` php
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 100],
            [['name'], 'unique'],
        ];
    }
```
