### ISSUE TITLE
Automatyczne dodawanie wartosci formularza

### ISSUE THREAD

**Issue by chomyczek** [mklemarczyk/yii-prezentacja#20]
Mamy tabele koszyk, jak dodać id obecnie zalogowanego uzytkownika automatycznie a nie recznie?
przyjmijmy ze koszyk ma pola :
`id, przedmiot, ilosc, uzytkownik_id`

**Comment by mklemarczyk** [comment]
Potrzebujesz edytować akcję [**kontrolera**](http://www.yiiframework.com/doc-2.0/guide-structure-controllers.html).
Możesz ją zacytować?

A informację o id zalogowanego użytkownika, można uzyskać za pomocą zmiennej:

``` php
Yii::$app->user->id
```

**Comment by chomyczek** [comment]
Akcja create:

``` php
    public function actionCreate()
    {
        $model = new KoszykPrzedmiot();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
```

**Comment by mklemarczyk** [comment]
Dane w zmiennej model, możesz edytować dopiero po załadowaniu danych z formularza, tj. po instrukcji:

``` php
$model->load(Yii::$app->request->post());
```

Aby wpisać id użytkownika do odpowiedniego pola w modelu wystarczy:

``` php
$model->uzytkownik_id = Yii::$app->user->id;
```

**Comment by chomyczek** [comment]
a co mam z tym zrobic jezeli mam load w if`ie?

**Comment by mklemarczyk** [comment]
Oh, na przykład to (rozłożyć go na dwa if'y i pomiędzy napisać instrukcję przypisania):

``` php
    public function actionCreate()
    {
        $model = new KoszykPrzedmiot();

        if ($model->load(Yii::$app->request->post())) {
            $model->uzytkownik_id = Yii::$app->user->id;
            if($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }
```

:warning: Notka: Dodatkowo musisz wcześniej uruchomić system logowania i rejestracji, który jest zaimplementowany w szkielecie aplikacji ( #10 )
