### ISSUE TITLE
Filtrowanie i sortowanie po polach z tabeli obcej

### ISSUE THREAD

**Issue by romety2** [mklemarczyk/yii-prezentacja#23]
Witam po raz kolejny :)

Używam wyszukiwarki utworzonej w CRUD Generator|Search Model Class jednak nie działa ona na klucze obce (po odpowiednich modyfikacjach, czyli takich by nie wyświetlał id) :(. Wiesz może jak zrobić by wyszukiwało te dane??

**Comment by mklemarczyk** [comment]
Jest to możliwe, jednak uprzedzam, że potrzeba do tego trochę cierpliwości.
Jesteś na to gotów(-owa)?

**Comment by romety2** [comment]
tak jest :) (gotów)

**Comment by mklemarczyk** [comment]
Musisz zacząć od modelu wyszukiwania.
Możesz zamieścić zawartość pliku modelu wyszukiwania?

Model wyszukiwania to ten, który służy za parametr dla widgetu [**GridView**](http://www.yiiframework.com/doc-2.0/guide-output-data-widgets.html#gridview).

``` php
    <?= GridView::widget([
        [...]
        'filterModel' => $searchModel,
        [...]
    ]); ?>
```

Może się nazywać na przykład `frontend/models/ZakupSeach`
Gdy generowałeś CRUD, jest tam opcja by wygenerować model wyszukiwania. (Trzeba było podać jego nazwę docelową)

---

## Instrukcja filtrów:
1. Potrzebne będą nowe zmienne publiczne w tym modelu (np. dla pracownik.imie pole pracownik_imie).
2. Należy dodać instrukcje innerJoin, celem złączenia danych z innych tabel.
3. Następnie dodać kryteria filtrowania uwzględniające nowe zmienne.
4. Sformatować kolumny w widoku, aby używały nowych zmiennych.

## Instrukcja sortowania:

W modelu wyszukiwania należy zdefiniować dodatkowe parametry sortowania za pomocą metody setSort obiektu ActiveDataProvider.

Przykład użycia:

``` php
        $dataProvider->setSort([
            'attributes' => array_merge(Zakup::attributes(), [
                'pracownik.imie' => [
                    'asc' => ['{{%pracownik}}.imie' => SORT_ASC],
                    'desc' => ['{{%pracownik}}.imie' => SORT_DESC],
                ],
            ]),
            'defaultOrder' => [
                'data' => SORT_DESC,
                'pracownik.imie' => SORT_ASC,
            ],
        ]);
```

Instrukcję `setSort` należy użyć bezpośrednio przed `$this->load($params);`.

**Comment by romety2** [comment]
Model wyszukiwania to ten z którego chce szukać :) ??

<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "boks".
 *
 * @property integer $id_boks
 * @property string $boks
 *
 * @property Zwierze[] $zwierzes
 */
class Boks extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'boks';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['boks'], 'required'],
            [['boks'], 'string', 'max' => 20]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_boks' => 'Id Boks',
            'boks' => 'Boks',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getZwierzes()
    {
        return $this->hasMany(Zwierze::className(), ['id_boks' => 'id_boks']);
    }
}

**Comment by mklemarczyk** [comment]
Nie, to ten który służy za parametr dla widgetu GridView.

```php
    <?= GridView::widget([
        [...]
        'filterModel' => $searchModel,
        [...]
    ]); ?>
```

**Comment by romety2** [comment]
Model wyszukiwania `ZwierzeSearch`

``` php
<?php

namespace common\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use common\models\Zwierze;

/**
 * ZwierzeSearch represents the model behind the search form about `common\models\Zwierze`.
 */
class ZwierzeSearch extends Zwierze
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_zwierze', 'id_wolontariusz', 'id_gatunek', 'id_boks'], 'integer'],
            [['imie', 'plec', 'data_przybycia', 'opis', 'adopcja'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Zwierze::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        $query->andFilterWhere([
            'id_zwierze' => $this->id_zwierze,
            'id_wolontariusz' => $this->id_wolontariusz,
            'id_gatunek' => $this->id_gatunek,
            'id_boks' => $this->id_boks,
            'data_przybycia' => $this->data_przybycia,
        ]);

        $query->andFilterWhere(['like', 'imie', $this->imie])
            ->andFilterWhere(['like', 'plec', $this->plec])
            ->andFilterWhere(['like', 'opis', $this->opis])
            ->andFilterWhere(['like', 'adopcja', $this->adopcja]);

        return $dataProvider;
    }
}
```

**Comment by mklemarczyk** [comment]
**Dla przykładu zaimplementujemy filtrowanie dla nazwy gatunku.**

``` php
<?php

namespace common\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use common\models\Zwierze;

/**
 * ZwierzeSearch represents the model behind the search form about `common\models\Zwierze`.
 */
class ZwierzeSearch extends Zwierze
{
    /**
     * @todo Dodajemy zmienną gatunek_nazwa
     */
    public $gatunek_nazwa;
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_zwierze', 'id_wolontariusz', 'id_gatunek', 'id_boks'], 'integer'],
            [['imie', 'plec', 'data_przybycia', 'opis', 'adopcja'], 'safe'],
            /**
             * @todo Umożliwiamy wprowadzanie danych do zmiennej gatunek_nazwa (wymagane dla zmiennych typu string)
             */
            [['gatunek_nazwa'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        /**
         * @todo Złaczamy tabelę gatunek
         */
        $query = Zwierze::find()
            ->innerJoin('{{%gatunek}}', '{{%gatunek}}.id = gatunek_id');

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        $query->andFilterWhere([
            'id_zwierze' => $this->id_zwierze,
            'id_wolontariusz' => $this->id_wolontariusz,
            'id_gatunek' => $this->id_gatunek,
            'id_boks' => $this->id_boks,
            'data_przybycia' => $this->data_przybycia,
        ]);

        $query->andFilterWhere(['like', 'imie', $this->imie])
            ->andFilterWhere(['like', 'plec', $this->plec])
            ->andFilterWhere(['like', 'opis', $this->opis])
            ->andFilterWhere(['like', 'adopcja', $this->adopcja]);

        /**
         * @todo Dodajemy filtr dla nowej zmiennej
         */
        $query->andFilterWhere(['like', '{{%gatunek}}.nazwa', $this->gatunek_nazwa]);

        return $dataProvider;
    }
}
```

---

Na koniec trzeba edytować widok `index`

Zwykłe pole danych w [**GridView**](http://www.yiiframework.com/doc-2.0/guide-output-data-widgets.html#gridview) definiujemy:

``` php
            [...]
            'gatunek.nazwa',
            [...]
```

Jednak, aby dodać własne pole filtrujące musimy zdefiniować w ten sposób:

``` php
            [...]
            [
                'attribute' => 'gatunek.nazwa',
                'filter' => Html::activeTextInput($searchModel, 'gatunek_nazwa', ['class' => 'form-control']),
            ],
            [...]
```

**Comment by romety2** [comment]
Spoko :) wysłałem Ci oba bo nie wiem który Ci będzie bardziej potrzebny :)

**Comment by mklemarczyk** [comment]
Czy wyjaśnienie jest wystarczające?

**Comment by romety2** [comment]
Dzieki wielkie będę Ci musiał chyba coś postawić za tą ciągłą pomoc ;), Tak jeszcze w ramach wyjaśnienia wysłałem to wysłałem Ci oba b chciałem połączyć zwierzątko z boksem i nie byłem pewien który Ci będzie potrzebny ale to co wysłałeś powinno wystarczyć ;) Dzieki jeszcze raz :)

**Comment by mklemarczyk** [comment]
To jeszcze nie koniec, jeszcze jeden krok do filtrowania. ;)

**Comment by romety2** [comment]
ok, potrze Ci coś jeszcze z mojej strony :) ??

**Comment by mklemarczyk** [comment]
Nie

**Comment by mklemarczyk** [comment]
Musisz edytować widok `index`

Zwykłe pole danych w GridView definiujemy:
```php
            [...]
            'gatunek.nazwa',
            [...]
```
