### ISSUE TITLE
Problem "Filtrowanie i sortowanie po polach z tabeli obcej"

### ISSUE THREAD

**Issue by romety2** [mklemarczyk/yii-prezentacja#24]
Witam próbowałem zrobić Twoim sposobem jednak mam następujący komunikat 

``` sql
Integrity constraint violation – yii\db\IntegrityException
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id_boks' in on clause is ambiguous
The SQL being executed was: SELECT COUNT(*) FROM `zwierze` INNER JOIN `boks` ON `boks`.id_boks = id_boks

Error Info: Array
(
    [0] => 23000
    [1] => 1052
    [2] => Column 'id_boks' in on clause is ambiguous
)
```

Wiesz może jaki jest powód :P ??
Problem jest tutaj

``` php
        $query = Zwierze::find()
        ->innerJoin('{{%boks}}', '{{%boks}}.id_boks = id_boks');
```

Czy powodem może być brak danych w encji zwierze ??

**Comment by mklemarczyk** [comment]
Wyraźnie napisano komunikat **Column 'id_boks' in on clause is ambiguous**. Użyłeś tej samej nazwy kolumn w obu tabelach.

:+1: Zalecenie: Klucze główne powinny nazywać się **id**, natomiast klucze obce **[nazwa_tabeli_obcej]_id**.

:disappointed: Innym rozwiązaniem problemu może być użycie nazwy tabeli w query:

``` php
$query = Zwierze::find()
    ->innerJoin('{{%boks}}', '{{%boks}}.id_boks = '.Zwierze::tableName().'.id_boks');
```

**Comment by romety2** [comment]
Ok działa dzięki ;) Jeszcze pytanie jak zmienić nazwę kolumny, Jeśli wolisz mogę utworzyć oddzielny issues

**Comment by mklemarczyk** [comment]
You need to create a new issue... :smile:
