### ISSUE TITLE
Filtrowanie i sortowanie wg pola łączonego z tabeli obcej

### ISSUE THREAD

**Issue by martin123154** [mklemarczyk/yii-prezentacja#26]
Ja chcialbym podłączyć sie do pytania romety2 - bo twój sposób działa gdy wyszukuje po jednym elemencie, jednak jak zrobić żeby działało gdy chce wyszukać po polach z tabeli obcej jeżeli są one złączone z dwóch elementów? Np Jeżeli mamy klucz obcy 'Klient' który składa sie z imienia i nazwiska owego klienta (wcześniej utworzony w modelu klienta: public function getNazwisk(){
    return $this->imie . ' ' . $this->nazwisko;)

**Comment by mklemarczyk** [comment]
Wyszukiwanie w ten sposób jest wysoko niezalecane.
Należałoby rozdzielić kolumny.

Note: Musiałbyś wyszukiwać jednym polem w dwóch kolumnach, co może powodować niezrozumienie systemu przez użytkownika, ponieważ będą różne wyniki gdy napisze `Maria`, `Kowalska`, `Matra Kowalska`, `Kowalska Marta`. Format wyszukiwania będzie zbyt trudny dla użytkownika. **Ponieważ będzie się spodziewał, że wszystkie powyższe hasła wyświetlą użytkownika Marta Kowalska**.

Dodatkowo polecam issues: #3, #23.
