### ISSUE TITLE
Ograniczenie daty do dnia dzisiejszego

### ISSUE THREAD

**Issue by ghost** [mklemarczyk/yii-prezentacja#27]
Jak zrobić ograniczenie na datę, żeby nie można było wprowadzić późniejszej daty niż dzień dzisiejszy ?

**Comment by mklemarczyk** [comment]
[**Date validator**](http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html#date) będzie posiadał opcje **min** i **max**, lecz dopiero w kolejnej wersji Yii (https://github.com/yiisoft/yii2/pull/8115)

Dlatego na chwilę obecną należy to wykonać za pomocą [**compare validator**](http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html#compare).

``` php
['date', 'compare', 'operator' => '<', 'compareValue' => date('Y-m-d')],
```

:warning: Format daty w funkcji **date** musi odpowiadać formatowi bazy danych.
