### ISSUE TITLE
Zmiana nagłówka kolumny (GridView) w widoku

### ISSUE THREAD

**Issue by romety2** [mklemarczyk/yii-prezentacja#28]
Jak zmienić nazwę kolumny w GridView?

Mam kolumnę zdefiniowaną w ten sposób (tak jak w #23):

``` php
            [...]
            [
                'attribute' => 'gatunek.nazwa',
                'filter' => Html::activeTextInput($searchModel, 'gatunek_nazwa', ['class' => 'form-control']),
            ],
            [...]
```

**Comment by mklemarczyk** [comment]
Gdy definiujemy kolumnę parametrycznie, wystarczy podać parametr `label`.

``` php
            [...]
            [
                'attribute' => 'gatunek.nazwa',
                'label' => 'Nazwa gatunku',
                'filter' => Html::activeTextInput($searchModel, 'gatunek_nazwa', ['class' => 'form-control']),
            ],
            [...]
```

**Comment by romety2** [comment]
eee czy ja dobrze rozumiem :> ?? bo chodzi o to ze mam domyślnie boks boks czyli nazwe tabli i kolumny wyświetlanej a chce mieć jeden boks :D. Nie działa ani tekst ani label :< ??

**Comment by mklemarczyk** [comment]
Nie rozumiem, możesz opisać strukturę bazy danych a potem zadać pytanie jeszcze raz?

**Comment by mklemarczyk** [comment]
Może inaczej, o której kolumnie mówisz?

**Comment by romety2** [comment]
Mowie kolumnie z pola filtrującego dajmy mam połączoną Boks ze Zwierzęciem kolumna w Boks kotar chce wyświetlić to Nazwa i w Zwierzęciu mam nazwe kolumny Boks Nazwa a chcialbym miec np samo Boks :).
![ggggg](https://cloud.githubusercontent.com/assets/5895702/7257632/605e0eda-e857-11e4-9ad7-d7255c02146a.png)

**Comment by romety2** [comment]
XD dzieki :D
