### ISSUE TITLE
Weryfikacja danych - Match Validator

### ISSUE THREAD

**Issue by chomyczek** [mklemarczyk/yii-prezentacja#29]
W modelu Uzytkownik ma m coś takiego:

``` php
    public function rules()
    {
        return [
            [['nazwa', 'email', 'haslo', 'ulica', 'nr_domu', 'miasto', 'kod_pocztowy'], 'required'],
            [['email', 'haslo', 'ulica', 'nr_domu', 'miasto', 'kod_pocztowy'], 'string', 'max' => 255],
            [['nazwa'],'string', 'min'=>3, 'max' => 255],
            [['nazwa'],'match', 'pattern'=>'/[a-z]{4}/u', 'message' => 'zly login',]
        ];
    }
```

co robie zle z tym patternem, że zawsze przechodz, znaczy tak jak jest teraz powinno pozwolić na wpisanie 4 liter od a do z a jeszeli wpisze cyfry albo 10 znaków to i tak pisze ze jest ok.

**Comment by mklemarczyk** [comment]
Standardowo wzorce służą do wyszukiwania.
Istnieją dwa dodatkowe znaki we wzorcach `^` - oznaczający początek oraz `$` - oznaczający koniec.

Aby wzorzec działał poprawnie w [**match validator**](http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html#match):

``` php
[['nazwa'],'match', 'pattern'=>'/^[a-z]{4}$/u', 'message' => 'zly login'],
```

:information_source: Dodatkowo ograniczenie długości znaków można określić jako [**string validator**](http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html#string):

``` php
[['nazwa'], 'string', 'length' => 4],
```

**Comment by chomyczek** [comment]
czyli to była kwestia dwuch znaczków :< dzieki
