### ISSUE TITLE
Problem z umieszczeniem wielu danych w jednym polu

### ISSUE THREAD

**Issue by mzweigert** [mklemarczyk/yii-prezentacja#3]
Mam 2 tabele, klient i adres. Tabela adres jest połączona z tabelą klient realacją wiele do wielu (klucz obcy idAdres znajduje się w tabeli klient).
Podczas wyswietlania klienta we frameworku, chcialbym aby adres (miasto,ulica,nr,kod) wyswietlal się w jednym polu, a nie w kilku - rozdzielonych od siebie.

kod modelu Klient.php

``` php
/**
 * This is the model class for table "klient".
 *
 * @property integer $id_klient
 * @property integer $idAdres
 * @property string $imie
 * @property string $nazwisko
 * @property string $data_dolaczenia
 * @property integer $dodatkowe_punkty
 *
 * @property Adres $idAdres0
 * @property Zamowienie[] $zamowienies
 */
```

kod z view.php (klienta)

``` php
<?= DetailView::widget([
    'model' => $model,
    'attributes' => [
        'id_klient',
        'idAdres',
        'imie',
        'nazwisko',
        'data_dolaczenia:date',
        'dodatkowe_punkty',
        'idAdres',
        'idAdres0.miasto',
        'idAdres0.ulica',
        'idAdres0.numer',
        'idAdres0.kod',
    ],
]) ?>
```

**Comment by mklemarczyk** [comment]
Aby to zrobić możesz napisać w [**modelu**](http://www.yiiframework.com/doc-2.0/guide-structure-models.html) pole wyliczeniowe.

Przykład: Załóżmy, że chcemy zrobić imie i nazwisko w jednym polu o nazwie nazwaKlienta.
W modelu będziemy potrzebowali funkcji:

``` php
public function getNazwaKlienta(){
    return $this->imie . ' ' . $this->nazwisko;
}
```

W widoku będziemy mogli tego użyć w ten sposób:

``` php
<?= DetailView::widget([
    'model' => $model,
    'attributes' => [
        [...]
        'nazwaKlienta',
        [...]
    ],
]) ?>
```

PS: W twoim przypadku pole wyliczeniowe będzie trzeba zaimplementować w [**modelu**](http://www.yiiframework.com/doc-2.0/guide-structure-models.html) odpowiedzialnym za tabelę z **adresem**, a nie tabelę odpowiedzialną za **klienta**.
