### ISSUE TITLE
Formatowanie waluty w widoku

### ISSUE THREAD

**Issue by chomyczek** [mklemarczyk/yii-prezentacja#30]
Jak zrobić dopisek waluty w widoku?

**Comment by mklemarczyk** [comment]
Do formatowanie waluty należy użyć [**formatera**](http://www.yiiframework.com/doc-2.0/guide-output-formatter.html).
W tym celu należy użyć aliasu `currency` w ten sam sposób jak `date`, `time` czy `datetime`.
