### ISSUE TITLE
Dane z modelu obcego (widok)

### ISSUE THREAD

**Issue by chomyczek** [mklemarczyk/yii-prezentacja#31]
Mam widok aktualizacji zamówienia, w któym wyświetlam formularz zamówienia.

Chciałbym wyświetlić w nagłówku H1 w widoku nazwę pracownika.

**Comment by mklemarczyk** [comment]
Jeśli chodzi o wyświetlenie danych relacyjnych z modelu w widoku.
Możesz posłużyć się zmienną `$model`, która reprezentuje instancję bieżącego zamówienia.

``` php
$model->pracownik->imie;
```
