### ISSUE TITLE
Sumowanie wartości w kolumnie

### ISSUE THREAD

**Issue by chomyczek** [mklemarczyk/yii-prezentacja#32]
jak znalezc wszystkie elementy o konkretnym id, następnie dodać ich wartości ceny tak by móc przypisać do zmiennej ich łączną sume?

**Comment by mklemarczyk** [comment]
Trudno mi odpowiedzieć bez znajomości struktury danych.

Ale wyszukiwanie to metoda where.
A suma to sum('[[nazwa kolumny]]')

Przykład użycia:

``` php
$cena_laczna = Zakup::find()
    ->where(['id' => 2])
    ->getPozycjas()
    ->sum('[[cena_brutto]]');
```
