### ISSUE TITLE
Własne dane w dropDownList() zamiast danych z bazy danych

### ISSUE THREAD

**Issue by chomyczek** [mklemarczyk/yii-prezentacja#33]
chce zrobic liste gotowych pozycji, typu Nowe albo wysłane i mam coś takiego

``` php
    <?= $form->field($model, 'status')->dropDownList( $items=[['Nowe'],['Wysłane']], $options = [] ) ?>
```

jak zrobić by 'Nowe' miało inną wartość niż 0 a najlepiej miało taką samą jak ona sama. przy okazji by była widoczna wyłącznie nazwa wybieranej pozycji a nie jej wartość

**Comment by mklemarczyk** [comment]
Na to pytanie jest już odpowiedź. Issue #5
