### ISSUE TITLE
Wyszukiwanie po polu z datą

### ISSUE THREAD

**Issue by romety2** [mklemarczyk/yii-prezentacja#35]
Wiesz może jak zrobić wyszukiwanie dat przy pomocy wyszukiwarki, gdyż domyślnie nie działa. Najlepiej dla formatu dd.mm.yyyy :D ??

**Comment by mklemarczyk** [comment]
Działa, jeśli nic nie zmieniłeś to traktuje datę tak samo jak string. Więc wyszukiwanie jest realizowane w formacie jakim reprezentuje datę baza danych.

Aby to zmienić musisz w modelu wyszukiwania dokonać konwersji formatu daty.

**Comment by romety2** [comment]
nic nie zmieniałem i nie działa :) nie wiem co jest tego powodem ale robiłem wszystko wg Twoich instrukcji :)

**Comment by mklemarczyk** [comment]
Wpisz jakąkolwiek datę w formacie yyyy-mm-dd, jeśli nie znajdzie nic załącz screeny, 1\* że rekord istnieje, 2\* że go nie wyszukało.

**Comment by romety2** [comment]
aaa ok zadziało jak wpisałem całą datę, myślałem że będzie dla kawałków daty typu wpisze 03 i pojawi się  2000-03-03 :D, ok dzięki możesz uznać temat za zamknięty :)

**Comment by mklemarczyk** [comment]
Niestety bez modyfikacji modelu wyszukiwania nie będzie działało w ten sposób.
Należałoby zweryfikować metody filtrujące i sformatować pole z datą w modelu wyszukiwania, aby umożliwić wyszukiwanie w inny sposób.
