### ISSUE TITLE
Problem z rejestracją - UnknownMethodException

### ISSUE THREAD

**Issue by romety2** [mklemarczyk/yii-prezentacja#36]
Po wykonaniu https://github.com/mklemarczyk/yii-prezentacja/issues/10 pojawia się komunikat :D

```
Unknown Method – yii\base\UnknownMethodException
Calling unknown method: common\models\User::setPassword()
```

wiesz może jak to naprawić ??

**Comment by mklemarczyk** [comment]
Ten sam problem co #25

**Comment by romety2** [comment]
Czyli musze "zmieniłem komputer i zacząłem od nowa nie korzystająć z tabeli User, teraz działą :P" Tak :D ??

**Comment by mklemarczyk** [comment]
:link: Ten sam problem co #25 #21 

:no_entry_sign: Nie możesz nadpisać pliku **User** poprzez wygenerowanie nowego modelu.
:warning: W szkielecie aplikacji istnieje już model **User**.

:information_source: Model ten posiada domyślnie funkcje umożliwiające poprawne logowanie i rejestrację. Możesz jedynie go rozbudowywać.

**Comment by romety2** [comment]
ok dzięki :)

**Comment by mklemarczyk** [comment]
Sorki za ilość emotek, ale #37 mnie zirytował.

**Comment by romety2** [comment]
Spoko nie dziwie się
