### ISSUE TITLE
Problem z wczytaniem stron po stworzeniu cruda itd

### ISSUE THREAD

**Issue by kreteda2** [mklemarczyk/yii-prezentacja#37]
Mam problem z ładowaniem stron po wykonaniu całej instrukcji 
mod_rewrite załadowany

img http://nfs-w.pl/Untitleddsadsad.jpg

![untitleddsadsad](https://cloud.githubusercontent.com/assets/12071113/7279441/57415d00-e91c-11e4-8d6a-e81ea7d6e606.jpg)

**Comment by mklemarczyk** [comment]
Podaj zawartość plików:
- `common/models/Sprzedaz.php`
- `frontend/controllers/SprzedazController.php`
- `frontend/view/sprzedaz/index.php`

Jeśli którykolwiek z plików nie istnieje lub nazywa się inaczej, oznacza to, że CRUD został źle wygenerowany (tj. dane w formularzu tworzenia zostały źle wprowadzone).

**Comment by kreteda2** [comment]
Dobra to chyba zalatwione, jest kolejny błąd

Controllery zamiast w frontend/controllers/ generują mi sie w common\models

to co wyszlo jak wkleiłem controller do forntend/controllers

![image](https://cloud.githubusercontent.com/assets/12071113/7281081/a1a909fa-e927-11e4-8ad6-89ded8ba6163.png)

**Comment by mklemarczyk** [comment]
Bo nie przeczytałeś instrukcji lub nie postępujesz zgodnie z filmem.
:blue_book: https://github.com/mklemarczyk/yii-prezentacja/wiki/Instrukcja#2-tworzenie-kontroler%C3%B3w

:warning: Zalecam przeczytać uważnie instrukcję, następnie zadawać pytanie.
