### ISSUE TITLE
zmiana id na cos innego

### ISSUE THREAD

**Issue by AChlebba** [mklemarczyk/yii-prezentacja#38]
![blad1](https://cloud.githubusercontent.com/assets/6032233/7283389/79bec56a-e936-11e4-93b7-ca2260ecb977.png)
jak próbuje zamienić np. 'id_ksiazka' na 'ksiazka.tytul' to wywala bład 
Getting unknown property: common\models\Wypozyczenie::ksiazka
o co chodzi ?

**Comment by mklemarczyk** [comment]
Sprawdź czy w modelu Wypozyczenie wygenerowała się funkcja getKsiazka.
Jeśli nie to musisz sprawdzić czy masz relacje w bazie danych.
Ewentualnie mogła przyjąć inną nazwę.

**Comment by AChlebba** [comment]
nie ma funkcji getKsiazka, a relacje powinny byc zaimportowałem sobie taką baze danych
![bazasql](https://cloud.githubusercontent.com/assets/6032233/7284029/f3240894-e93a-11e4-82fa-d54ce086e092.png)

**Comment by mklemarczyk** [comment]
Niestety MySQL chyba nie obsługuje tego formatu deklarowania kluczy obcych. Sprawdź w phpmyadmin czy referencje utworzyły się poprawnie.

**Comment by AChlebba** [comment]
no nie zrobiły się, to jak powinna wyglądać poprawna deklaracja klucza obcego ?

**Comment by mklemarczyk** [comment]
Jest opisana w pliku sql na repozytorium w folderze baza danych
