### ISSUE TITLE
Problem z wrzuceniem projektu na sigme

### ISSUE THREAD

**Issue by ghost** [mklemarczyk/yii-prezentacja#39]
Mam problem z wrzuceniem swojego projektu na sigme. Nie wiem jak ustawić różne prawa dla plików i katalogów, trochę tego za dużo, żeby robić to pojedynczo :). Próbowałem przydzielić prawa dla całego public_html na 777, ale po wpisaniu strony sigma.inf.ug.edu.pl/~smatyjas/advanced pokazuje błąd wczytania.

**Comment by mklemarczyk** [comment]
Musisz mieć prawa do katalogu domowego na co najmniej 711, pozostałe prawa do projektu polecam Ci nadać za pomocą filezilla.

:warning: Projekt podczas pracy może tworzyć pliki które mogą być trudne a czasem niemożliwe do usunięcia. (Niestety to problem konfiguracyjny Sigmy)

**Comment by mklemarczyk** [comment]
Polecam użyć skryptu do inicjacji praw dostępu.

**Comment by ghost** [comment]
Zrobiłem wszystko to co tutaj: https://github.com/mklemarczyk/yii-prezentacja/wiki/Yii-na-sigmie. Ogólnie projekt jest na sigmie, ale mógłbyś pokazać jak wrzucić przykładową tabelę np. klient na sigme ?

**Comment by mklemarczyk** [comment]
Tak samo jak tworzyłeś tabele w postgesql.
Ewentualnie za pomocą migracji też można utworzyć tabele.
:blue_book: https://github.com/mklemarczyk/yii-prezentacja/wiki/Yii-na-sigmie#migracja-bazy-danych-ma-postgesql-opcjonalnie
