### ISSUE TITLE
Polskie litery - nagłówki kolumn

### ISSUE THREAD

**Issue by mawalca** [mklemarczyk/yii-prezentacja#4]
Witam.
Mam pytanie. Jak zrobić polskie litery w nagłówkach kolumn w widokach?

**Comment by mklemarczyk** [comment]
Jeśli chodzi o polskie litery w nazwach kolumn, należy odwiedzić plik z [**modelem**](http://www.yiiframework.com/doc-2.0/guide-structure-models.html) (common/models/nazwa_tabeli.php).

Tam jest funkcja o nazwie [**attributeLabels**](http://www.yiiframework.com/doc-2.0/guide-structure-models.html#attribute-labels), która odpowiada za nagłówki kolumn.
Musisz poprawić te nazwy i zapisać plik z kodowaniem UTF-8.
