### ISSUE TITLE
jak sie pozbyc paska debuggera?

### ISSUE THREAD

**Issue by chomyczek** [mklemarczyk/yii-prezentacja#40]
jak sie pozbyc paska debuggera, ktory generuje bledy przy walidacji w3c?

**Comment by mklemarczyk** [comment]
W pliku konfiguracji masz component debug, wyszatrczy  że usuniesz jego konfigurację.

**Comment by mklemarczyk** [comment]
W pliku konfiguracji masz konfigurację komponentu `debug`, wyszatrczy że usuniesz jego konfigurację.
