### ISSUE TITLE
Problem z folderem assets

### ISSUE THREAD

**Issue by martin123154** [mklemarczyk/yii-prezentacja#42]
Postępowałem zgodnie z instrukcjami nt wrzucenia projektu na sigme jednak pojawił sie problem. 

w Momencie wykonywania skryptu yii chmod wyrzuca mi ogrom błędów związanych właśnie z znajdującymi sie tam plikami, oto przykład kilku z nich:

```
chmod: nie można zmienić uprawnień do „public_html/advanced/frontend/web/assets/193a86d7/yii.gridView.js”: Operacja niedozwolona
chmod: nie można zmienić uprawnień do „public_html/advanced/frontend/web/assets/193a86d7/yii.validation.js”: Operacja niedozwolona
chmod: nie można zmienić uprawnień do „public_html/advanced/frontend/web/assets/193a86d7/yii.js”: Operacja niedozwolona
chmod: nie można zmienić uprawnień do „public_html/advanced/frontend/web/assets/193a86d7/yii.captcha.js”: Operacja niedozwolona
chmod: nie można zmienić uprawnień do „public_html/advanced/frontend/web/assets/193a86d7/yii.activeForm.js”: Operacja niedozwolona
chmod: nie można zmienić uprawnień do „public_html/advanced/frontend/web/assets/eeaf9924”: Operacja niedozwolona
chmod: nie można zmienić uprawnień do „public_html/advanced/frontend/web/assets/eeaf9924/jquery.min.map”: Operacja niedozwolona
```

Jest ich więcej, tyczą sie wszystkich folderów (8) sie tam znajdujących, 
Zauważyłem też przy patrzeniu w baze że bootstrap.css który zmieniałem przy okazji robienia projektu nie jest odczytywany na sigmie (wszystko jest ustawione jakby domyślnie, jedyny css jaki mi działa to ten który nie znajduje sie w folderze assets). Sprawdzałem prawa dostępu, wszystkie są ustawione na 711 (użyłem   komendy  chmod 711 -R public_html na wypadek jakby jednak coś nie grało z prawami)

PS: Nie wiem czy to ma jakiś związek ale w momencie wrzucenia folderu advanced na sigme właśnie w assets pojawiły mi sie 3 foldery których to zawartości nie idzie w żaden sposób usunąć

**Comment by mklemarczyk** [comment]
Te foldery zostały utworzone przez PHP i nie jesteś ich właścicielem.
Właścicielem wszystkich plików utworzonych przez PHP jest `www-data`.
Można je usunąć jedynie z poziomu PHP.

:grey_exclamation: Dodatkowo nie możesz modyfikować żadnych plików w folderze assets, ponieważ wszelkie zmiany będą nadpisywane przez Yii (jest to jedynie katalog tymczasowy).

**Comment by mklemarczyk** [comment]
Skoro nie ma więcej pytać w tym temacie - zamykam.
