### ISSUE TITLE
cascade na sigmie

### ISSUE THREAD

**Issue by romety2** [mklemarczyk/yii-prezentacja#45]
Jak zrobić usuwanie cascade na sigmie :D ??
nie działa polecnie:
ALTER TABLE osobaADD CONSTRAINT osoba_adres FOREIGN KEY (id_adres) REFERENCES adres (id) ON DELETE CASCADE ON UPDATE CASCADE;

**Comment by mklemarczyk** [comment]
Dokumentacja PostrgeSQL

http://www.postgresql.org/docs/8.2/static/ddl-constraints.html

W przypadku używania migracji:

``` php
$this->addForeignKey('FK_post_uzytkownik', '{{post}}', 'uzytkownik_id', '{{uzytkownik}}', 'id', 'CASCADE', 'CASCADE');
```

http://www.yiiframework.com/doc-2.0/yii-db-querybuilder.html#addForeignKey()-detail

**Comment by romety2** [comment]
dzięki
