### ISSUE TITLE
Zabezpieczenie przed nie prawdziwa datą

### ISSUE THREAD

**Issue by romety2** [mklemarczyk/yii-prezentacja#46]
Gdy wpiszę nieprawdziwą datę NA SIGMIE pojawia się taki błąd 

```
SQLSTATE[22008]: Datetime field overflow: 7 BŁĄD: wartość pola daty/czasu poza zakresem: "2000-55-02"
HINT: Być może potrzebujesz innego ustawienia "datestyle".
The SQL being executed was: INSERT INTO "zwierze" ([edytowano], "data", [edytowano]") VALUES ([edytowano], '2000-55-02', [edytowano])

Error Info: Array
(
    [0] => 22008
    [1] => 7
    [2] => BŁĄD:  wartość pola daty/czasu poza zakresem: "2000-55-02"
HINT:  Być może potrzebujesz innego ustawienia "datestyle".
)
```

 wiesz może jak sprawdzić by komunikował w bardziej normalny sposób :P

**Comment by mklemarczyk** [comment]
Przedstawiony przez ciebie tekst to błąd wykonania. Programista powinien obsłużyć wszystkie błędy lub napisać kod w sposób by błędy nie występowały w ten sposób.

Powinieneś zaimplementować poprawnie weryfikację pól, aby informować użytkownika o popełnionym przez niego błędzie. Do daty możesz zastosować [**Date validator**](http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html#date) w [**modelu**](http://www.yiiframework.com/doc-2.0/guide-structure-models.html)

Przykład użycia:

``` php
['urodzony', 'date'],
```

:green_book: Więcej informacji: http://www.yiiframework.com/doc-2.0/guide-input-validation.html

**Comment by romety2** [comment]
dzieki :D
