### ISSUE TITLE
Brak tabel na sigmie

### ISSUE THREAD

**Issue by Dawid93** [mklemarczyk/yii-prezentacja#47]
Problem z obsługą cruda na sigmie po migracji.

**Comment by mklemarczyk** [comment]
Zweryfikuj wielkość liter, wszystkie tabele i nazwy kolumn w bazie danych powinny być pisane wyłącznie małymi literami.
Zweryfikuj czy łączysz się z odpowiednią bazą danych, sprawdź czy baza danych istnieje.
