### ISSUE TITLE
Formularz - własna lista rozwijalna

### ISSUE THREAD

**Issue by mawalca** [mklemarczyk/yii-prezentacja#5]
Kolejne pytanie.
Jak stworzyć listę rozwijalną w formularzu tworzenia nowego elementu, w której byłyby pozycje nie z innej tabeli, tylko moje własne?

**Comment by mklemarczyk** [comment]
Listę rozwijają tworzymy za pomocą metody [**dropDownList**](http://www.yiiframework.com/doc-2.0/yii-widgets-activefield.html#dropDownList%28%29-detail).

Która potrzebuje tablicy z danymi w formacie

``` php
$lista = [
    1 => 'Początkujący',
    2 => 'Średnio zaawansowany',
    3 => 'Ekspert',
];
```

Listę te można zapisać w modelu w nowej metodzie aby mieć potem dostęp do tej listy. Podobnie jak wygląda funkcja [**attributeLabels**](http://www.yiiframework.com/doc-2.0/guide-structure-models.html#attribute-labels) tylko jako funkcje statyczna.

Dla przykładu:
W [**modelu**](http://www.yiiframework.com/doc-2.0/guide-structure-models.html):

``` php
public static function getPoziomy()
{
    return [
        1 => 'Początkujący',
        2 => 'Średnio zaawansowany',
        3 => 'Ekspert',
    ];
}
```

W [**formularzu**](http://www.yiiframework.com/doc-2.0/guide-input-forms.html):

``` php
    <?= $form->field($model, 'poziom')->dropDownList($model->getPoziomy()); ?>
```
