### ISSUE TITLE
Problem z dropDownList w actionUpdate

### ISSUE THREAD

**Issue by kpalkowska** [mklemarczyk/yii-prezentacja#6]
Mój kod w kontrolerze wygląda tak (na zasadzie tego co w tutorialu dla actionCreate):    

``` php
public function actionUpdate($id){

        $model = $this->findModel($id);

        $albumy = Album::find()
            ->orderBy('tytul')
            ->all();

        $albumy = ArrayHelper::map($albumy, 'id', 'tytul');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'albumy' => $albumy, 
            ]);
        }
    }
```

Jednak dla update to nie działa (brak błędów, ale nie zmienia danych w polu, gdzie jest lista rozwijana). Wiesz może dlaczego?

**Comment by mklemarczyk** [comment]
Czy możesz dołączyć zawartość [**widoków**](http://www.yiiframework.com/doc-2.0/guide-structure-views.html) **update.php** i **_form.php** dla tego [**kontrolera**](http://www.yiiframework.com/doc-2.0/guide-structure-controllers.html)?

**Comment by kpalkowska** [comment]
view.php : 

<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Piosenka */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Piosenki'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="piosenka-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Popraw'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Usun'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'tytul',
            'slowa:ntext',
            'album_id',
        ],
    ]) ?>

</div>

**Comment by kpalkowska** [comment]
_form.php

``` php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Piosenka */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="piosenka-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'tytul')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'slowa')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'album')->dropDownList($albumy) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Dodaj') : Yii::t('app', 'Popraw'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
```

**Comment by mklemarczyk** [comment]
Przepraszam Cię serdecznie, miałem na myśli widok update.php

**Comment by kpalkowska** [comment]
update.php

``` php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Piosenka */

$this->title = Yii::t('app', 'Popraw: {modelClass} ', [
    'modelClass' => 'Piosenka',
]) . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Piosenki'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Popraw');
?>
<div class="piosenka-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'albumy' => $albumy,
    ]) ?>

</div>
```

**Comment by mklemarczyk** [comment]
To mam kilka pytań:
1. Jakie dane wpisujesz do formularza?
2. Czy po naciśnięciu zapisz przechodzi na stronę piosenka/view?
3. Czy możesz pokazać plik z modelem piosenki?

**Comment by kpalkowska** [comment]
1. Gdy z listy rozwijalnej wybieram inny album niż jest obecnie, moja zmiana nie jest uwzględniona.
2. Tak, przechodzi.

piosenka.php

``` php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "piosenka".
 *
 * @property integer $id
 * @property string $tytul
 * @property string $slowa
 * @property integer $album_id
 *
 * @property Album $album
 */
class Piosenka extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'piosenka';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tytul', 'slowa', 'album_id'], 'required'],
            [['slowa'], 'string'],
            [['album_id'], 'integer'],
            [['tytul'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'tytul' => Yii::t('app', 'Tytul'),
            'slowa' => Yii::t('app', 'Slowa'),
            'album_id' => Yii::t('app', 'Album ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAlbum()
    {
        return $this->hasOne(Album::className(), ['id' => 'album_id']);
    }
}
```

**Comment by mklemarczyk** [comment]
W modelu twoje pole nazywa sie **album_id**, które jest relacją do tabeli album.
A w formularzu wstawiasz **id** **albumu** do pola **album**, które **_nie**_ istnieje w bazie danych.

Samo pole album istnieje w [**modelu tabeli**](http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#working-with-relational-data) i jest wirtualne. Realizuje je funkcja **getAlbum**.

Powinnaś napisać w formularzu:

``` php
    <?= $form->field($model, 'album_id')->dropDownList($albumy) ?>
```

zamiast

``` php
    <?= $form->field($model, 'album')->dropDownList($albumy) ?>
```
