### ISSUE TITLE
Zmiana języka ":date".

### ISSUE THREAD

**Issue by srzeppa** [mklemarczyk/yii-prezentacja#8]
Jak zmienić język wyświetlanych miesięcy na polski?

**Comment by mklemarczyk** [comment]
W konfiguracji, gdzie konfigurowałeś język aplikacji należy zdefiniować konfigurację:
(tj. _/common/config/main.php_)

``` php
'components' => [
    'formatter' => [
        'dateFormat' => 'dd.MM.yyyy',
        'decimalSeparator' => ',',
        'thousandSeparator' => ' ',
        'currencyCode' => 'PLN',
   ],
],
```

Note: Niestety nie ma możliwości przetłumaczenia nazw miesięcy na język polski bez użycia rozszerzenia intl dla PHP.
